version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2000:3000"
    restart: always
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    privileged: true
    volumes:
      - /var/lib/tor:/var/lib/tor
    environment:
      - PYTHONUNBUFFERED=1
